#!/bin/bash
tmpDir=$(mktemp -d /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/execution/tmp.XXXXXX)
chmod 777 $tmpDir
export _JAVA_OPTIONS=-Djava.io.tmpdir=$tmpDir
export TMPDIR=$tmpDir

(
cd /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/execution
svaba run -p 4 -t /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/inputs/Users/dawsonet/sandbox/firecloud-tools/SvABA/../delly/alt.sorted.bam -n /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/inputs/Users/dawsonet/sandbox/firecloud-tools/SvABA/../delly/ref.sorted.bam --hp -G /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/inputs/Users/dawsonet/sandbox/firecloud-tools/SvABA/../delly/mega.orig.fa -k /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/inputs/Users/dawsonet/sandbox/firecloud-tools/SvABA/reg.bed -a sample
)
echo $? > /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/execution/rc.tmp
(
cd /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/execution

)
sync
mv /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/execution/rc.tmp /cromwell-executions/svabaSomatic/4e749086-4189-4fe7-86f9-05e909aa79b2/call-svabaCall/execution/rc
